[package]
name = "eveng"
version = "0.1.1"
edition = "2024"
rust-version = "1.88"
authors = ["Piya Gehi <piya@orgnizedmess.net>"]
license = "MIT"
description = "An API Client for EVE-NG"
readme = "README.md"
homepage = "https://github.com/orgnizedmess/eveng.rs"
repository = "https://github.com/orgnizedmess/eveng.rs"
keywords = ["api", "eveng", "eve-ng"]
categories = ["api-bindings", "network-programming"]

[dependencies]
reqwest = { version = "0.13.4", features = ["json", "cookies", "rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_repr = "0.1.21"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["time"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
